name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/**

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Print directory structure
        run: |
          echo "Directory structure after downloading artifact:"
          tree ./dist

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/dist/_esp32/static_files.h
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}.

            Includes the following changes:
            ${{ github.event.head_commit.message }}
